// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookTextMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookTextMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookTextMessage is a mock of WebhookTextMessage interface.
type MockWebhookTextMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookTextMessageMockRecorder
	isgomock struct{}
}

// MockWebhookTextMessageMockRecorder is the mock recorder for MockWebhookTextMessage.
type MockWebhookTextMessageMockRecorder struct {
	mock *MockWebhookTextMessage
}

// NewMockWebhookTextMessage creates a new mock instance.
func NewMockWebhookTextMessage(ctrl *gomock.Controller) *MockWebhookTextMessage {
	mock := &MockWebhookTextMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookTextMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookTextMessage) EXPECT() *MockWebhookTextMessageMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockWebhookTextMessage) Chat() botinput.WebhookChat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.WebhookChat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookTextMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookTextMessage)(nil).Chat))
}

// IntID mocks base method.
func (m *MockWebhookTextMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookTextMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookTextMessage)(nil).IntID))
}

// IsEdited mocks base method.
func (m *MockWebhookTextMessage) IsEdited() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEdited")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEdited indicates an expected call of IsEdited.
func (mr *MockWebhookTextMessageMockRecorder) IsEdited() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEdited", reflect.TypeOf((*MockWebhookTextMessage)(nil).IsEdited))
}

// StringID mocks base method.
func (m *MockWebhookTextMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookTextMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookTextMessage)(nil).StringID))
}

// Text mocks base method.
func (m *MockWebhookTextMessage) Text() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	return ret0
}

// Text indicates an expected call of Text.
func (mr *MockWebhookTextMessageMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockWebhookTextMessage)(nil).Text))
}
