// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookVoiceMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookVoiceMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookVoiceMessage is a mock of WebhookVoiceMessage interface.
type MockWebhookVoiceMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookVoiceMessageMockRecorder
	isgomock struct{}
}

// MockWebhookVoiceMessageMockRecorder is the mock recorder for MockWebhookVoiceMessage.
type MockWebhookVoiceMessageMockRecorder struct {
	mock *MockWebhookVoiceMessage
}

// NewMockWebhookVoiceMessage creates a new mock instance.
func NewMockWebhookVoiceMessage(ctrl *gomock.Controller) *MockWebhookVoiceMessage {
	mock := &MockWebhookVoiceMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookVoiceMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookVoiceMessage) EXPECT() *MockWebhookVoiceMessageMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockWebhookVoiceMessage) Chat() botinput.WebhookChat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.WebhookChat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookVoiceMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookVoiceMessage)(nil).Chat))
}

// IntID mocks base method.
func (m *MockWebhookVoiceMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookVoiceMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookVoiceMessage)(nil).IntID))
}

// StringID mocks base method.
func (m *MockWebhookVoiceMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookVoiceMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookVoiceMessage)(nil).StringID))
}
