// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookPhotoMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookPhotoMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookPhotoMessage is a mock of WebhookPhotoMessage interface.
type MockWebhookPhotoMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookPhotoMessageMockRecorder
	isgomock struct{}
}

// MockWebhookPhotoMessageMockRecorder is the mock recorder for MockWebhookPhotoMessage.
type MockWebhookPhotoMessageMockRecorder struct {
	mock *MockWebhookPhotoMessage
}

// NewMockWebhookPhotoMessage creates a new mock instance.
func NewMockWebhookPhotoMessage(ctrl *gomock.Controller) *MockWebhookPhotoMessage {
	mock := &MockWebhookPhotoMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookPhotoMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookPhotoMessage) EXPECT() *MockWebhookPhotoMessageMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockWebhookPhotoMessage) Chat() botinput.WebhookChat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.WebhookChat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookPhotoMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).Chat))
}

// IntID mocks base method.
func (m *MockWebhookPhotoMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookPhotoMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).IntID))
}

// StringID mocks base method.
func (m *MockWebhookPhotoMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookPhotoMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).StringID))
}
