// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookStickerMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookStickerMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookStickerMessage is a mock of WebhookStickerMessage interface.
type MockWebhookStickerMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookStickerMessageMockRecorder
	isgomock struct{}
}

// MockWebhookStickerMessageMockRecorder is the mock recorder for MockWebhookStickerMessage.
type MockWebhookStickerMessageMockRecorder struct {
	mock *MockWebhookStickerMessage
}

// NewMockWebhookStickerMessage creates a new mock instance.
func NewMockWebhookStickerMessage(ctrl *gomock.Controller) *MockWebhookStickerMessage {
	mock := &MockWebhookStickerMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookStickerMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookStickerMessage) EXPECT() *MockWebhookStickerMessageMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockWebhookStickerMessage) Chat() botinput.WebhookChat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.WebhookChat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookStickerMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookStickerMessage)(nil).Chat))
}

// IntID mocks base method.
func (m *MockWebhookStickerMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookStickerMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookStickerMessage)(nil).IntID))
}

// StringID mocks base method.
func (m *MockWebhookStickerMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookStickerMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookStickerMessage)(nil).StringID))
}
