// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookSharedUsersMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookSharedUsersMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookSharedUsersMessage is a mock of WebhookSharedUsersMessage interface.
type MockWebhookSharedUsersMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSharedUsersMessageMockRecorder
	isgomock struct{}
}

// MockWebhookSharedUsersMessageMockRecorder is the mock recorder for MockWebhookSharedUsersMessage.
type MockWebhookSharedUsersMessageMockRecorder struct {
	mock *MockWebhookSharedUsersMessage
}

// NewMockWebhookSharedUsersMessage creates a new mock instance.
func NewMockWebhookSharedUsersMessage(ctrl *gomock.Controller) *MockWebhookSharedUsersMessage {
	mock := &MockWebhookSharedUsersMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookSharedUsersMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSharedUsersMessage) EXPECT() *MockWebhookSharedUsersMessageMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockWebhookSharedUsersMessage) Chat() botinput.WebhookChat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.WebhookChat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookSharedUsersMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).Chat))
}

// GetSharedUsers mocks base method.
func (m *MockWebhookSharedUsersMessage) GetSharedUsers() []botinput.SharedUserMessageItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedUsers")
	ret0, _ := ret[0].([]botinput.SharedUserMessageItem)
	return ret0
}

// GetSharedUsers indicates an expected call of GetSharedUsers.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetSharedUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedUsers", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetSharedUsers))
}

// IntID mocks base method.
func (m *MockWebhookSharedUsersMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).IntID))
}

// StringID mocks base method.
func (m *MockWebhookSharedUsersMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).StringID))
}
